version: '3.8'

services:
  arxiv-tracker:
    build: .
    container_name: arxiv-paper-tracker
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_TO=${EMAIL_TO}
    volumes:
      - ./src/papers:/app/src/papers
      - ./src/logs:/app/src/logs
      - ./src/conclusion.md:/app/src/conclusion.md
    restart: unless-stopped
    networks:
      - arxiv-network

  # 可选：添加 Redis 用于缓存
  redis:
    image: redis:7-alpine
    container_name: arxiv-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - arxiv-network

  # 可选：添加 PostgreSQL 用于数据存储
  postgres:
    image: postgres:15-alpine
    container_name: arxiv-postgres
    environment:
      - POSTGRES_DB=arxiv_tracker
      - POSTGRES_USER=arxiv_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-arxiv_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - arxiv-network

volumes:
  redis_data:
  postgres_data:

networks:
  arxiv-network:
    driver: bridge 