name: 🚀 部署可行性测试

on:
  workflow_dispatch:
    inputs:
      setup_type:
        description: '设置类型'
        required: true
        default: 'check_secrets'
        type: choice
        options:
        - check_secrets
        - test_configuration
        - run_analysis

jobs:
  setup-guide:
    runs-on: ubuntu-latest
    steps:
    - name: 📋 检查配置状态
      run: |
        echo "🔍 检查 DeepSeek AI 和邮件配置状态..."
        echo ""
        
        # 检查DeepSeek API配置 (必需)
        if [ -n "${{ secrets.DEEPSEEK_API_KEY }}" ]; then
          echo "✅ DEEPSEEK_API_KEY: 已配置 (💰 DeepSeek - 高性价比AI分析)"
          ai_configured=true
        else
          echo "❌ DEEPSEEK_API_KEY: 未配置"
          ai_configured=false
        fi
        
        if [ "$ai_configured" = false ]; then
          echo "❌ 未配置DeepSeek API密钥"
          secrets_status="missing"
        else
          echo "🎯 DeepSeek AI配置完成，系统将使用高性价比的DeepSeek模型进行分析"
        fi
        
        # 检查必需的邮件配置
        if [ -z "${{ secrets.SMTP_SERVER }}" ]; then
          echo "❌ SMTP_SERVER: 未配置"
          secrets_status="missing"
        else
          echo "✅ SMTP_SERVER: 已配置"
        fi
        
        if [ -z "${{ secrets.SMTP_USERNAME }}" ]; then
          echo "❌ SMTP_USERNAME: 未配置"
          secrets_status="missing"
        else
          echo "✅ SMTP_USERNAME: 已配置"
        fi
        
        if [ -z "${{ secrets.SMTP_PASSWORD }}" ]; then
          echo "❌ SMTP_PASSWORD: 未配置"
          secrets_status="missing"
        else
          echo "✅ SMTP_PASSWORD: 已配置"
        fi
        
        if [ -z "${{ secrets.EMAIL_FROM }}" ]; then
          echo "❌ EMAIL_FROM: 未配置"
          secrets_status="missing"
        else
          echo "✅ EMAIL_FROM: 已配置"
        fi
        
        if [ -z "${{ secrets.EMAIL_TO }}" ]; then
          echo "❌ EMAIL_TO: 未配置"
          secrets_status="missing"
        else
          echo "✅ EMAIL_TO: 已配置"
        fi
        
        echo ""
        if [ "$secrets_status" = "missing" ]; then
          echo "⚠️  发现缺少的配置项！"
          echo ""
          echo "📝 配置步骤："
          echo "1. 进入仓库 Settings → Secrets and variables → Actions"
          echo "2. 点击 'New repository secret'"
          echo "3. 🤖 添加DeepSeek AI配置 (必需)："
          echo "   💰 DEEPSEEK_API_KEY: DeepSeek API密钥"
          echo "   📖 获取地址: https://platform.deepseek.com/"
          echo "4. 📧 添加邮件配置 (必需)："
          echo "   - SMTP_SERVER: 邮件服务器 (如: smtp.gmail.com)"
          echo "   - SMTP_USERNAME: 邮箱账号"
          echo "   - SMTP_PASSWORD: 邮箱授权码"
          echo "   - EMAIL_FROM: 发件人邮箱"
          echo "   - EMAIL_TO: 收件人邮箱"
          echo ""
          echo "📖 详细配置指南: https://github.com/${{ github.repository }}/blob/main/docs/setup/DEEPSEEK_SETUP_GUIDE.md"
          exit 1
        else
          echo "🎉 配置验证成功！DeepSeek AI和邮件配置均已就绪"
          echo "💡 提示: 系统将使用DeepSeek进行高质量论文分析"
        fi

  test-configuration:
    runs-on: ubuntu-latest
    if: github.event.inputs.setup_type == 'test_configuration'
    needs: setup-guide
    steps:
    - uses: actions/checkout@v4
    
    - name: 🐍 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: 📦 安装 uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
    
    - name: 🔧 安装依赖
      run: uv sync --frozen
    
    - name: 🔍 验证配置
      env:
        # DeepSeek AI配置
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        DEEPSEEK_MODEL: ${{ secrets.DEEPSEEK_MODEL || 'deepseek-chat' }}
        # 邮件配置
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        SMTP_PORT: ${{ secrets.SMTP_PORT || '587' }}
      run: |
        echo "🔍 运行配置验证和测试..."
        cd scripts && uv run python validate_env.py

  run-test-analysis:
    runs-on: ubuntu-latest
    if: github.event.inputs.setup_type == 'run_analysis'
    needs: setup-guide
    steps:
    - uses: actions/checkout@v4
    
    - name: 🐍 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: 📦 安装 uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
    
    - name: 🔧 安装依赖
      run: uv sync --frozen
    
    - name: 🧪 运行测试分析
      env:
        # DeepSeek AI配置
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        DEEPSEEK_MODEL: ${{ secrets.DEEPSEEK_MODEL || 'deepseek-chat' }}
        # 邮件配置
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        # 测试配置
        MAX_PAPERS: 3  # 测试时只分析3篇论文
        SEARCH_DAYS: 1
        ANALYSIS_TYPE: comprehensive
      run: |
        echo "🚀 运行测试分析（少量论文）..."
        cd src && uv run python main.py 