name: 测试

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: 安装uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: 设置Python
      run: uv python install ${{ matrix.python-version }}
    
    - name: 创建虚拟环境
      run: uv venv --python ${{ matrix.python-version }}
    
    - name: 安装依赖
      run: uv pip install -e .
    
    - name: 创建测试环境变量
      run: |
        echo "DEEPSEEK_API_KEY=test-key-12345678901234567890" >> $GITHUB_ENV
        echo "SMTP_SERVER=smtp.gmail.com" >> $GITHUB_ENV
        echo "SMTP_USERNAME=test@example.com" >> $GITHUB_ENV
        echo "SMTP_PASSWORD=test-password" >> $GITHUB_ENV
        echo "EMAIL_FROM=test@example.com" >> $GITHUB_ENV
        echo "EMAIL_TO=test@example.com" >> $GITHUB_ENV
        echo "MAX_PAPERS=3" >> $GITHUB_ENV
        echo "SEARCH_DAYS=1" >> $GITHUB_ENV
    
    - name: 运行组件测试
      run: uv run src/tests/test_components.py
    
    - name: 运行单模型测试
      run: uv run src/tests/test_single_model.py
    
    - name: 检查代码格式
      run: |
        uv pip install black isort
        black --check src/
        isort --check-only src/ 